const PUZZLES = [
  // ── Rat Run ──────────────────────────────────────────────────────────────

  // Phase 1
  { name: "Primer",          url: "", group: "Rat Run", experiment: 1,  codename: "PURPLE",  color: "#7952B3", darkText: false },
  { name: "Tenacity",        url: "", group: "Rat Run", experiment: 2,  codename: "BEIGE",   color: "#D4B896", darkText: true  },
  { name: "Double Dutch",    url: "", group: "Rat Run", experiment: 3,  codename: "ORANGE",  color: "#E8933A", darkText: false },
  { name: "Borderline",      url: "", group: "Rat Run", experiment: 4,  codename: "BLUE",    color: "#5BA4CF", darkText: false },
  { name: "Disparity",       url: "", group: "Rat Run", experiment: 5,  codename: "RED",     color: "#CC2222", darkText: false },
  { name: "Equilibrium",     url: "", group: "Rat Run", experiment: 6,  codename: "OLIVE",   color: "#697A3A", darkText: false },
  { name: "Multiple Choice", url: "", group: "Rat Run", experiment: 7,  codename: "BLACK",   color: "#1A1A1A", darkText: false },
  { name: "Discontinuous",   url: "", group: "Rat Run", experiment: 8,  codename: "GOLD",    color: "#B89520", darkText: false },
  { name: "Shock Value",     url: "", group: "Rat Run", experiment: 9,  codename: "CRIMSON", color: "#C0243C", darkText: false },
  { name: "Sensored",        url: "", group: "Rat Run", experiment: 10, codename: "LIME",    color: "#C8D86A", darkText: true  },
  // Phase 2
  { name: "Limited Addition",    url: "", group: "Rat Run", experiment: 11, codename: "INDIGO",    color: "#4B0082", darkText: false },
  { name: "Visiting Order",      url: "", group: "Rat Run", experiment: 12, codename: "TEAL",      color: "#2D9E8C", darkText: false },
  { name: "Triskaidekaphilia",   url: "", group: "Rat Run", experiment: 13, codename: "BRONZE",    color: "#A87C2A", darkText: false },
  { name: "Thermoregulation",    url: "", group: "Rat Run", experiment: 14, codename: "SLATE",     color: "#5E6B80", darkText: false },
  { name: "Connectedness",       url: "", group: "Rat Run", experiment: 15, codename: "MAGENTA",   color: "#D42BAA", darkText: false },
  { name: "Schrödinger's Rat",   url: "", group: "Rat Run", experiment: 16, codename: "TURQUOISE", color: "#4CC8C8", darkText: true  },
  { name: "Trapdoors",           url: "", group: "Rat Run", experiment: 17, codename: "PEACH",     color: "#EDB88C", darkText: true  },
  { name: "Mirror Maze",         url: "", group: "Rat Run", experiment: 18, codename: "GREEN",     color: "#38A848", darkText: false },
  { name: "Brainwaves",          url: "", group: "Rat Run", experiment: 19, codename: "MAROON",    color: "#7A1818", darkText: false },
  { name: "Gifted",              url: "", group: "Rat Run", experiment: 20, codename: "WHITE",     color: "#F0F0E8", darkText: true,  bordered: true  },

  { name: "51 Years Later", url: "", group: "Rat Run", special: true, color: "#6870C4" },

  // Phase 3
  { name: "Friendly",             url: "", group: "Rat Run", experiment: 21, codename: "PINK",     color: "#F080C0", darkText: false },
  { name: "Copyrat",              url: "", group: "Rat Run", experiment: 22, codename: "CYAN",     color: "#3EC4F0", darkText: false },
  { name: "Notable Differences",  url: "", group: "Rat Run", experiment: 23, codename: "AMBER",    color: "#C89820", darkText: false },
  { name: "Between You and Me",   url: "", group: "Rat Run", experiment: 24, codename: "MINT",     color: "#8EDCC8", darkText: true  },
  { name: "Mod Cons",             url: "", group: "Rat Run", experiment: 25, codename: "CERULEAN", color: "#3A90C8", darkText: false },
  { name: "Hit and Miss",         url: "", group: "Rat Run", experiment: 26, codename: "TAN",      color: "#B09050", darkText: false },
  { name: "Productivity",         url: "", group: "Rat Run", experiment: 27, codename: "BROWN",    color: "#5A3A18", darkText: false },
  { name: "Hypothesis",           url: "", group: "Rat Run", experiment: 28, codename: "VIOLET",   color: "#7040C8", darkText: false },
  { name: "Counterbalance",       url: "", group: "Rat Run", experiment: 29, codename: "KHAKI",    color: "#909040", darkText: false },
  { name: "Star Rats",            url: "", group: "Rat Run", experiment: 30, codename: "SILVER",   color: "#B0B8C8", darkText: false },
  { name: "Equivalence",          url: "", group: "Rat Run", experiment: 31, codename: "VIRIDIAN", color: "#2A9060", darkText: false },
  { name: "Veracity",             url: "", group: "Rat Run", experiment: 32, codename: "NAVY",     color: "#1A2878", darkText: false },
  { name: "Hot and Cold",        url: "", group: "Rat Run", experiment: 33, codename: "MAUVE",     color: "#7A3868", darkText: false },
  { name: "On Reflection",       url: "", group: "Rat Run", experiment: 34, codename: "AQUA",      color: "#3ECEB4", darkText: false },
  { name: "Locked Out",          url: "", group: "Rat Run", experiment: 35, codename: "GREY",      color: "#5E6878", darkText: false },
  { name: "Alternating Currant", url: "", group: "Rat Run", experiment: 36, codename: "LAVENDER",  color: "#A888D4", darkText: false },
  
  { name: "One Year Earlier", url: "", group: "Rat Run", special: true, color: "#E0D4A8", darkText: true },

  { name: "Fruitful",            url: "", group: "Rat Run", experiment: 37, codename: "BURGUNDY",  color: "#6B1030", darkText: false },
  { name: "Synchronicity",       url: "", group: "Rat Run", experiment: 38, codename: "YELLOW",    color: "#EAEA48", darkText: true,  bordered: true },
  { name: "Together Apart",      url: "", group: "Rat Run", experiment: 39, codename: "VERMILION", color: "#CC4420", darkText: false, completed: false },

  // ── Puzzled Pint ─────────────────────────────────────────────────────────
  // completed: true only on packs where the meta was solved
  { name: "Head of the Pints", url: "", group: "Puzzled Pint", year: 2026, month: "May" },
  { name: "The Beetles", url: "", group: "Puzzled Pint", year: 2026, month: "April" },
  { name: "Escape Room", url: "", group: "Puzzled Pint", year: 2026, month: "March" },
  { name: "Murder Mystery", url: "", group: "Puzzled Pint", year: 2026, month: "February", completed: true },
  { name: "Grateful Dead", url: "", group: "Puzzled Pint", year: 2026, month: "January" },
  { name: "Meta (2025)", url: "", group: "Puzzled Pint", year: 2025, isMeta: true },
  { name: "The Legend of Zelda", url: "", group: "Puzzled Pint", year: 2025, month: "December" },
  { name: "Catan", url: "", group: "Puzzled Pint", year: 2025, month: "November" },
  { name: "Constellations", url: "", group: "Puzzled Pint", year: 2025, month: "October", completed: true },
  { name: "Rome", url: "", group: "Puzzled Pint", year: 2025, month: "September" },
  { name: "Orville Peck", url: "", group: "Puzzled Pint", year: 2025, month: "August" },
  { name: "Puzzled Pint's 15th Anniversary", url: "", group: "Puzzled Pint", year: 2025, month: "July" },
  { name: "Game Shows", url: "", group: "Puzzled Pint", year: 2025, month: "June" },
  { name: "Artificial Intelligence", url: "", group: "Puzzled Pint", year: 2025, month: "May" },
  { name: "Night Out at the Puzzleria", url: "", group: "Puzzled Pint", year: 2025, month: "April" },
  { name: "The Monkey King", url: "", group: "Puzzled Pint", year: 2025, month: "March" },
  { name: "Birds", url: "", group: "Puzzled Pint", year: 2025, month: "February" },
  { name: "Nursery Rhymes", url: "", group: "Puzzled Pint", year: 2025, month: "January" },
  { name: "Meta (2024)", url: "", group: "Puzzled Pint", year: 2024, isMeta: true },
  { name: "Shapes", url: "", group: "Puzzled Pint", year: 2024, month: "December", completed: true },
  { name: "Classic Games", url: "", group: "Puzzled Pint", year: 2024, month: "November" },
  { name: "Shopping Spree", url: "", group: "Puzzled Pint", year: 2024, month: "October", completed: true },
  { name: "Choose Your Own Adventure", url: "", group: "Puzzled Pint", year: 2024, month: "September" },
  { name: "The Phantom Tollbooth", url: "", group: "Puzzled Pint", year: 2024, month: "August" },
  { name: "Road Trip", url: "", group: "Puzzled Pint", year: 2024, month: "July" },
  { name: "Sushi", url: "", group: "Puzzled Pint", year: 2024, month: "June" },
  { name: "Bart Simpson", url: "", group: "Puzzled Pint", year: 2024, month: "May" },
  { name: "The Magnus Archives", url: "", group: "Puzzled Pint", year: 2024, month: "April" },
  { name: "Mathematics", url: "", group: "Puzzled Pint", year: 2024, month: "March" },
  { name: "Afternoon Tea", url: "", group: "Puzzled Pint", year: 2024, month: "February", completed: true },
  { name: "Animal Casino", url: "", group: "Puzzled Pint", year: 2024, month: "January" },
  { name: "Meta (2023)", url: "", group: "Puzzled Pint", year: 2023, isMeta: true },
  { name: "Over the Garden Wall", url: "", group: "Puzzled Pint", year: 2023, month: "December" },
  { name: "Harvest Festival", url: "", group: "Puzzled Pint", year: 2023, month: "November" },
  { name: "Nobel Prizes", url: "", group: "Puzzled Pint", year: 2023, month: "October" },
  { name: "Quantum Physics", url: "", group: "Puzzled Pint", year: 2023, month: "September" },
  { name: "Questionable Letters", url: "", group: "Puzzled Pint", year: 2023, month: "August" },
  { name: "Christmas in July", url: "", group: "Puzzled Pint", year: 2023, month: "July" },
  { name: "Liquid Measures", url: "", group: "Puzzled Pint", year: 2023, month: "June" },
  { name: "Taco Tuesday", url: "", group: "Puzzled Pint", year: 2023, month: "May" },
  { name: "Codes", url: "", group: "Puzzled Pint", year: 2023, month: "April" },
  { name: "Not Another D&D Podcast", url: "", group: "Puzzled Pint", year: 2023, month: "March" },
  { name: "Robots", url: "", group: "Puzzled Pint", year: 2023, month: "February" },
  { name: "Five Nights at Freddy's", url: "", group: "Puzzled Pint", year: 2023, month: "January" },
  { name: "Meta (2022)", url: "", group: "Puzzled Pint", year: 2022, isMeta: true },
  { name: "Cats", url: "", group: "Puzzled Pint", year: 2022, month: "December" },
  { name: "Soccer World Cup", url: "", group: "Puzzled Pint", year: 2022, month: "November" },
  { name: "Special Characters", url: "", group: "Puzzled Pint", year: 2022, month: "October" },
  { name: "7 Deadly Sins", url: "", group: "Puzzled Pint", year: 2022, month: "September", completed: true },
  { name: "The Expanse", url: "", group: "Puzzled Pint", year: 2022, month: "August" },
  { name: "Squid Game", url: "", group: "Puzzled Pint", year: 2022, month: "July" },
  { name: "Jurassic Park", url: "", group: "Puzzled Pint", year: 2022, month: "June" },
  { name: "Dogs", url: "", group: "Puzzled Pint", year: 2022, month: "May" },
  { name: "Miyazaki", url: "", group: "Puzzled Pint", year: 2022, month: "April" },
  { name: "Internet Shopping", url: "", group: "Puzzled Pint", year: 2022, month: "March" },
  { name: "Spiritfarer", url: "", group: "Puzzled Pint", year: 2022, month: "February" },
  { name: "Avatar: The Last Airbender", url: "", group: "Puzzled Pint", year: 2022, month: "January" },
  { name: "Meta (2021)", url: "", group: "Puzzled Pint", year: 2021, isMeta: true },
  { name: "Gilligan's Island", url: "", group: "Puzzled Pint", year: 2021, month: "December" },
  { name: "Seven Wonders of the Ancient World", url: "", group: "Puzzled Pint", year: 2021, month: "November" },
  { name: "Condiments", url: "", group: "Puzzled Pint", year: 2021, month: "October" },
  { name: "Tenet", url: "", group: "Puzzled Pint", year: 2021, month: "September" },
  { name: "Vikings", url: "", group: "Puzzled Pint", year: 2021, month: "August" },
  { name: "Agatha Christie's Poirot", url: "", group: "Puzzled Pint", year: 2021, month: "July" },
  { name: "Chess", url: "", group: "Puzzled Pint", year: 2021, month: "June" },
  { name: "Steven Universe", url: "", group: "Puzzled Pint", year: 2021, month: "May" },
  { name: "Greek Mythology", url: "", group: "Puzzled Pint", year: 2021, month: "April" },
  { name: "Life in 2020", url: "", group: "Puzzled Pint", year: 2021, month: "March" },
  { name: "A Series of Unfortunate Events", url: "", group: "Puzzled Pint", year: 2021, month: "February" },
  { name: "PuzzFeed", url: "", group: "Puzzled Pint", year: 2021, month: "January" },
  { name: "Meta (2020)", url: "", group: "Puzzled Pint", year: 2020, isMeta: true },
  { name: "The Grinch", url: "", group: "Puzzled Pint", year: 2020, month: "December" },
  { name: "Scooby-Doo", url: "", group: "Puzzled Pint", year: 2020, month: "November" },
  { name: "Seasons", url: "", group: "Puzzled Pint", year: 2020, month: "October" },
  { name: "Scholhouse Roch", url: "", group: "Puzzled Pint", year: 2020, month: "September" },
  { name: "The Great British Baking Show", url: "", group: "Puzzled Pint", year: 2020, month: "August" },
  { name: "Puzzled Pint's 10th Anniversary", url: "", group: "Puzzled Pint", year: 2020, month: "July" },
  { name: "Modern Board Games", url: "", group: "Puzzled Pint", year: 2020, month: "June" },
  { name: "Dr. Seuss", url: "", group: "Puzzled Pint", year: 2020, month: "May" },
  { name: "Magic", url: "", group: "Puzzled Pint", year: 2020, month: "April" },
  { name: "Frankie & Louie", url: "", group: "Puzzled Pint", year: 2020, month: "March" },
  { name: "Circular Reasoning", url: "", group: "Puzzled Pint", year: 2020, month: "February" },
  { name: "Neko Atsume", url: "", group: "Puzzled Pint", year: 2020, month: "January" },
  { name: "Meta (2019)", url: "", group: "Puzzled Pint", year: 2019, isMeta: true },
  { name: "Die Hard", url: "", group: "Puzzled Pint", year: 2019, month: "December" },
  { name: "Music", url: "", group: "Puzzled Pint", year: 2019, month: "November" },
  { name: "Haunted House", url: "", group: "Puzzled Pint", year: 2019, month: "October" },
  { name: "Dimensional Diversions", url: "", group: "Puzzled Pint", year: 2019, month: "September" },
  { name: "The Muppet Show", url: "", group: "Puzzled Pint", year: 2019, month: "August" },
  { name: "The Space Age", url: "", group: "Puzzled Pint", year: 2019, month: "July" },
  { name: "The Crystal Maze", url: "", group: "Puzzled Pint", year: 2019, month: "June" },
  { name: "High School", url: "", group: "Puzzled Pint", year: 2019, month: "May" },
  { name: "Head to Head", url: "", group: "Puzzled Pint", year: 2019, month: "April" },
  { name: "The Dark Crystal", url: "", group: "Puzzled Pint", year: 2019, month: "March" },
  { name: "Art Heist", url: "", group: "Puzzled Pint", year: 2019, month: "February", completed: true },
  { name: "Friends", url: "", group: "Puzzled Pint", year: 2019, month: "January" },
  { name: "Meta (2018)", url: "", group: "Puzzled Pint", year: 2018, isMeta: true },
  { name: "The Nightmare Before Christmas", url: "", group: "Puzzled Pint", year: 2018, month: "December" },
  { name: "Da Vinci", url: "", group: "Puzzled Pint", year: 2018, month: "November" },
  { name: "Zoo Theft", url: "", group: "Puzzled Pint", year: 2018, month: "October" },
  { name: "Labyrinth", url: "", group: "Puzzled Pint", year: 2018, month: "September" },
  { name: "Pokémon", url: "", group: "Puzzled Pint", year: 2018, month: "August" },
  { name: "KANGAROO", url: "", group: "Puzzled Pint", year: 2018, month: "July" },
  { name: "Road Trip", url: "", group: "Puzzled Pint", year: 2018, month: "June" },
  { name: "Ampersands", url: "", group: "Puzzled Pint", year: 2018, month: "May" },
  { name: "Pintcoin", url: "", group: "Puzzled Pint", year: 2018, month: "April" },
  { name: "Harry Potter", url: "", group: "Puzzled Pint", year: 2018, month: "March" },
  { name: "Stargate", url: "", group: "Puzzled Pint", year: 2018, month: "February" },
  { name: "Stranger Things", url: "", group: "Puzzled Pint", year: 2018, month: "January" },
  { name: "Meta (2017)", url: "", group: "Puzzled Pint", year: 2017, isMeta: true },
  { name: "Secret Messages", url: "", group: "Puzzled Pint", year: 2017, month: "December" },
  { name: "Charlie and the Chocolate Factory", url: "", group: "Puzzled Pint", year: 2017, month: "November" },
  { name: "Dracula", url: "", group: "Puzzled Pint", year: 2017, month: "October" },
  { name: "Wedding", url: "", group: "Puzzled Pint", year: 2017, month: "September" },
  { name: "Destiny", url: "", group: "Puzzled Pint", year: 2017, month: "August" },
  { name: "Game of Thrones", url: "", group: "Puzzled Pint", year: 2017, month: "July" },
  { name: "The Prisoner", url: "", group: "Puzzled Pint", year: 2017, month: "June" },
  { name: "Pintopia Press", url: "", group: "Puzzled Pint", year: 2017, month: "May" },
  { name: "Playing Cards", url: "", group: "Puzzled Pint", year: 2017, month: "April" },
  { name: "Alice in Wonderland", url: "", group: "Puzzled Pint", year: 2017, month: "March" },
  { name: "Valentine's Day", url: "", group: "Puzzled Pint", year: 2017, month: "February" },
  { name: "Hamilton", url: "", group: "Puzzled Pint", year: 2017, month: "January" },
  { name: "Meta (2016)", url: "", group: "Puzzled Pint", year: 2016, isMeta: true },
  { name: "Dungeons & Dragons", url: "", group: "Puzzled Pint", year: 2016, month: "December" },
  { name: "I Puzzled", url: "", group: "Puzzled Pint", year: 2016, month: "November" },
  { name: "Election", url: "", group: "Puzzled Pint", year: 2016, month: "October" },
  { name: "Rats", url: "", group: "Puzzled Pint", year: 2016, month: "September" },
  { name: "Star Trek", url: "", group: "Puzzled Pint", year: 2016, month: "August" },
  { name: "Secret Societies", url: "", group: "Puzzled Pint", year: 2016, month: "July" },
  { name: "Pintopia Brewery Tours", url: "", group: "Puzzled Pint", year: 2016, month: "June" },
  { name: "Parks and Recreation", url: "", group: "Puzzled Pint", year: 2016, month: "May" },
  { name: "Queen's Birthday", url: "", group: "Puzzled Pint", year: 2016, month: "April" },
  { name: "Comic Book Mystery", url: "", group: "Puzzled Pint", year: 2016, month: "March" },
  { name: "Shel Silverstein", url: "", group: "Puzzled Pint", year: 2016, month: "February" },
  { name: "Crime Scene", url: "", group: "Puzzled Pint", year: 2016, month: "January" },
  { name: "Meta (2015)", url: "", group: "Puzzled Pint", year: 2015, isMeta: true },
  { name: "Mad Men", url: "", group: "Puzzled Pint", year: 2015, month: "December" },
  { name: "The Big Lebowski", url: "", group: "Puzzled Pint", year: 2015, month: "November" },
  { name: "Mystery Month", url: "", group: "Puzzled Pint", year: 2015, month: "October" },
  { name: "Doctor Who", url: "", group: "Puzzled Pint", year: 2015, month: "September" },
  { name: "Semaphore", url: "", group: "Puzzled Pint", year: 2015, month: "August" },
  { name: "Portland", url: "", group: "Puzzled Pint", year: 2015, month: "July" },
  { name: "TV", url: "", group: "Puzzled Pint", year: 2015, month: "June" },
  { name: "Ex Machina", url: "", group: "Puzzled Pint", year: 2015, month: "May" },
  { name: "The A-Team", url: "", group: "Puzzled Pint", year: 2015, month: "April" },
  { name: "Mythology", url: "", group: "Puzzled Pint", year: 2015, month: "March" },
  { name: "Phobias", url: "", group: "Puzzled Pint", year: 2015, month: "February" },
  { name: "X-Men", url: "", group: "Puzzled Pint", year: 2015, month: "January" },
  { name: "Reason's Greetings", url: "", group: "Puzzled Pint", year: 2014, month: "December" },
  { name: "Ancient Egypt", url: "", group: "Puzzled Pint", year: 2014, month: "November" },
  { name: "Back to the Future", url: "", group: "Puzzled Pint", year: 2014, month: "October" },
  { name: "Let's Talk About…", url: "", group: "Puzzled Pint", year: 2014, month: "September" },
  { name: "Moving Day", url: "", group: "Puzzled Pint", year: 2014, month: "August" },
  { name: "Monty Python and the Holy Grail", url: "", group: "Puzzled Pint", year: 2014, month: "July" },
  { name: "The DoubleClicks", url: "", group: "Puzzled Pint", year: 2014, month: "June" },
  { name: "The Princess Bride", url: "", group: "Puzzled Pint", year: 2014, month: "May" },
  { name: "Mix Tape", url: "", group: "Puzzled Pint", year: 2014, month: "April" },
  { name: "Casino", url: "", group: "Puzzled Pint", year: 2014, month: "March" },
  { name: "Spinal Tap", url: "", group: "Puzzled Pint", year: 2014, month: "February" },
  { name: "Transportation", url: "", group: "Puzzled Pint", year: 2014, month: "January" },
  { name: "Hitchhiker's Guide to the Galaxy", url: "", group: "Puzzled Pint", year: 2013, month: "December" },
  { name: "Five Senses", url: "", group: "Puzzled Pint", year: 2013, month: "November" },
  { name: "Sherlock", url: "", group: "Puzzled Pint", year: 2013, month: "October" },
  { name: "Bar Games", url: "", group: "Puzzled Pint", year: 2013, month: "September" },
  { name: "Magazines", url: "", group: "Puzzled Pint", year: 2013, month: "August" },
  { name: "Spies", url: "", group: "Puzzled Pint", year: 2013, month: "July" },
  { name: "Twin Peaks", url: "", group: "Puzzled Pint", year: 2013, month: "June" },
  { name: "Arrested Development", url: "", group: "Puzzled Pint", year: 2013, month: "May" },
  { name: "Marijuana", url: "", group: "Puzzled Pint", year: 2013, month: "April" },
  { name: "Jeopardy", url: "", group: "Puzzled Pint", year: 2013, month: "March" },
  { name: "Clue", url: "", group: "Puzzled Pint", year: 2013, month: "February" },
  { name: "Apocalypse", url: "", group: "Puzzled Pint", year: 2013, month: "January" },
  { name: "Disney Star Wars", url: "", group: "Puzzled Pint", year: 2012, month: "December" },
  { name: "Webcomics", url: "", group: "Puzzled Pint", year: 2012, month: "November" },
  { name: "Dogs", url: "", group: "Puzzled Pint", year: 2012, month: "October" },
  { name: "Eights", url: "", group: "Puzzled Pint", year: 2012, month: "September" },
  { name: "Wartron Games", url: "", group: "Puzzled Pint", year: 2012, month: "August" },
  { name: "Birthday Party Games", url: "", group: "Puzzled Pint", year: 2012, month: "July" },
  { name: "Bikes", url: "", group: "Puzzled Pint", year: 2012, month: "June" },
  { name: "Water Safety Month", url: "", group: "Puzzled Pint", year: 2012, month: "May" },
  { name: "Time Travel", url: "", group: "Puzzled Pint", year: 2012, month: "April" },
  { name: "Wedding Day", url: "", group: "Puzzled Pint", year: 2012, month: "March" },
  { name: "Wedding Planning", url: "", group: "Puzzled Pint", year: 2012, month: "February" },
  { name: "New Year's Day", url: "", group: "Puzzled Pint", year: 2012, month: "January" },
  { name: "Office Party", url: "", group: "Puzzled Pint", year: 2011, month: "December" },
  { name: "Election", url: "", group: "Puzzled Pint", year: 2011, month: "November" },
  { name: "School Exams", url: "", group: "Puzzled Pint", year: 2011, month: "October" },
  { name: "Outer Space", url: "", group: "Puzzled Pint", year: 2011, month: "September" },
  { name: "Round and Round", url: "", group: "Puzzled Pint", year: 2011, month: "August" },
  { name: "Puzzled Pint's 1st Anniversary", url: "", group: "Puzzled Pint", year: 2011, month: "July" },
  { name: "Flags", url: "", group: "Puzzled Pint", year: 2011, month: "June" },
  { name: "Board Games", url: "", group: "Puzzled Pint", year: 2011, month: "May" },
  { name: "Condiments", url: "", group: "Puzzled Pint", year: 2011, month: "April" },
  { name: "Shakespeare", url: "", group: "Puzzled Pint", year: 2011, month: "March" },
  { name: "First Date", url: "", group: "Puzzled Pint", year: 2011, month: "February" },
  { name: "Bar Games", url: "", group: "Puzzled Pint", year: 2011, month: "January" },
  { name: "Holidays", url: "", group: "Puzzled Pint", year: 2010, month: "December" },
  { name: "Napkins/ Magic/ Video Games", url: "", group: "Puzzled Pint", year: 2010, month: "November" },
  { name: "Beer", url: "", group: "Puzzled Pint", year: 2010, month: "October" },
  { name: "Pirates", url: "", group: "Puzzled Pint", year: 2010, month: "September" },
  { name: "Food", url: "", group: "Puzzled Pint", year: 2010, month: "August" },
  { name: "First Puzzled Pint", url: "", group: "Puzzled Pint", year: 2010, month: "July" },

  // ── Jane Street ──────────────────────────────────────────────────────────
  // { name: "...", url: "https://...", group: "Jane Street" },

  // ── Other Hunt ───────────────────────────────────────────────────────────
  // { name: "...", url: "https://...", group: "Other Hunt" },
];
