const CONCERTS = [
  { artist: "Sigrid",          venue: "Roundhouse",           city: "London", date: "2026-03-13", openers: [], with: ["Oliver"] },
  { artist: "Lorde",           venue: "The O2",               city: "London", date: "2025-11-17", openers: ["The Japanese House"], with: ["Oliver", "Devangini"] },
  { artist: "Katy Perry",      venue: "The O2",               city: "London", date: "2025-10-14", openers: [], with: ["Oliver"] },
  { artist: "Rose Gray",       venue: "Village Underground",  city: "London", date: "2025-10-13", openers: [], with: ["Oliver"] },
  { artist: "Erika Vikman",    venue: "The Garage",           city: "London", date: "2025-10-04", openers: [], with: ["Devangini"] },
  { artist: "Lady Gaga",       venue: "The O2",               city: "London", date: "2025-10-02", openers: [], with: ["Oliver", "Devangini"] },
  { artist: "BLACKPINK",       venue: "Wembley Stadium",      city: "London", date: "2025-08-15", openers: [], with: ["Oliver", "Felix", "Wenlan"] },
  { artist: "Camila Cabello",  venue: "Eventim Apollo",       city: "London", date: "2025-07-08", openers: [], with: ["Oliver", "Felix", "Wenlan"] },
  { artist: "Dua Lipa",        venue: "Wembley Stadium",          city: "London", date: "2025-06-20", openers: ["Dove Cameron"], guests: ["Jamiroquai"], with: ["Oliver"] },
  { artist: "Beyoncé",         venue: "Tottenham Hotspur Stadium", city: "London", date: "2025-06-05", openers: [], with: ["Oliver", "Felix", "Wenlan"] },
  { artist: "The Japanese House", venue: "Christchurch",           city: "Oxford",    date: "2025-06-21", openers: [], note: "Christchurch May Ball headliner", with: ["Oliver", "Daniel", "Avish"] },
  { festival: "BST Hyde Park", venue: "Hyde Park",                 city: "London", date: "2025-06-27", headliners: ["Olivia Rodrigo"], support: ["girl in red", "The Last Dinner Party", "Between Friends"], guests: ["Ed Sheeran"], with: ["Oliver", "Avish", "Wenlan", "Felix"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-22", openers: ["Say Now", "DJ Adam Theo"], with: ["Devangini"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-19", openers: ["DJ Adam Theo"], with: ["Oliver"] },
  { artist: "Nemo",            venue: "O2 Academy Islington", city: "London", date: "2025-11-13", openers: ["Punchbag"], with: ["Oliver"] },
  { artist: "Zara Larsson",    venue: "OVO Arena Wembley",    city: "London", date: "2025-11-05", openers: ["Omar Rudberg"], with: ["Oliver"] },
  { festival: "BST Hyde Park",         venue: "Hyde Park", city: "London",    date: "2025-07-05", headliners: ["Sabrina Carpenter"], support: ["Clairo", "beabadoobee"], with: ["Oliver", "Daniel", "Wenlan"] },
  { artist: "Charli XCX",         venue: "HERE at Outernet",        city: "London", date: "2024-06-07", openers: [], with: ["Oliver"] },
  { artist: "Olivia Rodrigo",     venue: "The O2",                  city: "London", date: "2024-05-14", openers: ["Remi Wolf"], with: ["Oliver", "George", "Wenlan"] },
  { artist: "KEiiNO",             venue: "Royal Vauxhall Tavern",   city: "London", date: "2024-04-06", openers: [] },
  { artist: "Griff",              venue: "Roundhouse",               city: "London", date: "2024-04-02", openers: [] },
  { artist: "Allie X",            venue: "Rough Trade East",         city: "London", date: "2024-02-28", openers: [], with: ["Devangini"] },
  { artist: "Zara Larsson",       venue: "Roundhouse",               city: "London", date: "2024-02-22", openers: ["Yaeger"], with: ["Oliver"] },
  { artist: "Kim Petras",         venue: "Eventim Apollo",           city: "London", date: "2024-02-19", openers: ["Alex Chapman", "Georgia"], with: ["Oliver"] },
  { artist: "Alessandra",         venue: "Heaven",                   city: "London", date: "2024-02-16", openers: [], with: ["Oliver", "Devangini", "Felix", "Wenlan"] },
  { artist: "Cornelia Jakobs",    venue: "The Garage",               city: "London", date: "2024-02-01", openers: ["Siobhán Winifred"], with: ["Devangini"] },
  { artist: "Daði Freyr",         venue: "O2 Shepherd's Bush Empire", city: "London", date: "2023-12-07", openers: ["Blusher"], with: ["Devangini"] },
  { artist: "Käärijä",            venue: "Roundhouse",               city: "London", date: "2023-10-23", openers: [], with: ["Oliver"] },
  { artist: "TWICE",              venue: "The O2",                   city: "London", date: "2023-09-07", openers: [], with: ["Wenlan"] },
  { artist: "Netta",              venue: "The Garage",               city: "London", date: "2023-09-01", openers: [], with: ["Josh"] },
  { artist: "Japanese Breakfast", venue: "Roundhouse",               city: "London", date: "2023-06-27", openers: ["Indigo De Souza"], with: ["Mum"] },
  { artist: "Beyoncé",            venue: "Tottenham Hotspur Stadium", city: "London", date: "2023-06-04", openers: [], with: ["Oliver"] },
  { festival: "Eurovision Song Contest (Semi-Final 1 - Jury Show)", venue: "M&S Bank Arena", city: "Liverpool", date: "2023-05-08", artists: ["Rita Ora", "Alessandra", "Alyosha", "Dion Cooper", "Käärijä", "La Zarra", "Let 3", "Loreen", "Lord of the Lost", "Luke Black", "Marco Mengoni", "Mia Nicolai", "Mimicat", "Noa Kirel", "Pasha Parfeni", "Rebecca Ferguson", "Remo Forrer", "Sudden Lights", "The Busker", "The Hardkiss", "TuralTuranX", "Vesna", "Wild Youth"], with: ["Oliver", "Tai", "Kyara"] },
  { artist: "Cornelia Jakobs",    venue: "Lafayette",                city: "London",    date: "2023-05-16", openers: [], with: ["Devangini"] },
  { artist: "KEiiNO",             venue: "Lush",                     city: "Liverpool", date: "2023-05-08", openers: [], with: ["Oliver", "Tai", "Kyara"] },
  { festival: "Eurovision in Concert", venue: "AFAS Live", city: "Amsterdam", date: "2023-04-15", artists: ["Albina & Familja Kelmendi", "Alessandra", "Alika", "Blanca Paloma", "Brunette", "Diljá", "Dion Cooper", "Gustaph", "Joker Out", "Katrina & The Waves", "Käärijä", "Lord of the Lost", "Loreen", "Mae Muller", "Mia Nicolai", "Monika Linkytė", "Pasha Parfeni", "Piqued Jacks", "Reiley", "Remo Forrer", "SALENA", "Sudden Lights", "TEYA", "Theodor Andrei", "The Busker", "TuralTuranX", "TVORCHI", "Vesna", "Voyager", "Wild Youth"], with: ["Oliver", "Avish"] },
  { festival: "London Eurovision Party", venue: "HERE at Outernet", city: "London", date: "2023-04-16", artists: ["Alessandra", "Alika", "Bilal Hassani", "Blanca Paloma", "Diljá", "Eldar Qasimov", "Freya Skye", "Joker Out", "Käärijä", "KEiiNO", "Let 3", "Loreen", "Luke Black", "Mae Muller", "MELOVIN", "Mimicat", "Monika Linkytė", "Pasha Parfeni", "Piqued Jacks", "Reiley", "SALENA", "Senhit", "Tamara", "TEYA", "Theodor Andrei", "The Busker", "TuralTuranX", "Vesna", "Voyager", "Wild Youth"], with: ["Oliver"] },
  { artist: "Shea Couleé",        venue: "Heaven",                   city: "London",    date: "2023-04-21", openers: ["GESS"], with: ["Devangini"] },
  { artist: "Ava Max",            venue: "O2 Shepherd's Bush Empire", city: "London",   date: "2023-04-19", openers: ["Emlyn"], with: ["Oliver"] },
  { artist: "Hayley Kiyoko",      venue: "Melkweg",                  city: "Amsterdam", date: "2023-04-13", openers: [], with: ["Oliver"] },
  { artist: "Sam Ryder",          venue: "Eventim Apollo",           city: "London",    date: "2023-03-30", openers: ["Charlotte Jane"] },
  { artist: "Lizzo",              venue: "The O2",                   city: "London",    date: "2023-03-16", openers: ["Joy Crookes"], with: ["Oliver"] },
  { artist: "Lizzo",              venue: "The O2",                   city: "London",    date: "2023-03-15", openers: ["Joy Crookes"], with: ["Oliver"] },
  { artist: "Carly Rae Jepsen",   venue: "Alexandra Palace",         city: "London",    date: "2023-02-15", openers: ["Lewis Ofman"], with: ["Oliver", "Avish"] },
  { artist: "Caroline Polachek",  venue: "Eventim Apollo",           city: "London",    date: "2023-02-14", openers: ["Doss"], with: ["Oliver"] },
  { artist: "Amanda Tenfjord",    venue: "Omeara",                   city: "London",    date: "2023-02-08", openers: ["Louis Coupe"] },
  { artist: "BLACKPINK",          venue: "The O2",                   city: "London",    date: "2022-12-01", openers: [], with: ["Oliver"] },
  { artist: "Sigrid",             venue: "OVO Arena Wembley",        city: "London",    date: "2022-11-12", openers: ["Tommy Lefroy", "Skaar"], with: ["Oliver", "Avish", "Kyara", "Tai"] },
  { artist: "Rina Sawayama",      venue: "O2 Academy Brixton",       city: "London",    date: "2022-10-26", openers: ["Tom Rasmussen", "Joesef"], with: ["Oliver", "Kyara", "Avish"] },
  { artist: "Rina Sawayama",      venue: "PRYZM",                    city: "London",    date: "2022-09-14", openers: [], with: ["Oliver"] },
  { artist: "Lady Gaga",          venue: "Tottenham Hotspur Stadium", city: "London",   date: "2022-07-29", openers: [], with: ["Oliver"] },
  { artist: "Carly Rae Jepsen",   venue: "Somerset House",           city: "London",    date: "2022-07-11", openers: [], with: ["Avish"] },
  { artist: "Billie Eilish",      venue: "The O2",                   city: "London",    date: "2022-06-26", openers: ["girl in red"], with: ["Oliver"] },
  { artist: "Charli XCX",        venue: "PRYZM",                    city: "London",    date: "2022-06-24", openers: ["Daine"], with: ["Oliver", "Avish"] },
  { artist: "Charli XCX",        venue: "Alexandra Palace",         city: "London",    date: "2022-05-19", openers: ["yeule"], guests: ["Caroline Polachek"], with: ["Oliver", "Kyara"] },
  { artist: "Little Mix",        venue: "The O2",                   city: "London",    date: "2022-05-13", openers: ["Since September"], members: ["Jade", "Leigh-Anne"] },
  { artist: "Dua Lipa",          venue: "The O2",                   city: "London",    date: "2022-05-03", openers: ["Griff", "Angèle"], with: ["Oliver", "Avish", "Tai"] },
  { artist: "Against the Current", venue: "Electric Ballroom",      city: "London",    date: "2022-04-10", openers: ["Yours Truly", "Halflives"], with: ["Oliver", "Avish"] },
  { artist: "AURORA",            venue: "O2 Academy Brixton",       city: "London",    date: "2022-04-06", openers: ["Metteson"], with: ["Oliver"] },
  { artist: "Lorde",              venue: "Alexandra Palace",         city: "London",    date: "2022-06-28", openers: ["Marlon Williams"], with: ["Oliver"] },
  { artist: "Lorde",              venue: "Roundhouse",               city: "London",    date: "2022-06-01", openers: ["Marlon Williams"], with: ["Oliver"] },
  { artist: "Olivia Rodrigo",     venue: "Eventim Apollo",           city: "London",    date: "2022-07-06", openers: ["Baby Queen"], guests: ["Natalie Imbruglia"], with: ["Oliver"] },
  { festival: "BST Hyde Park",    venue: "Hyde Park",                city: "London",    date: "2022-07-01", headliners: ["Adele"], support: ["Gabrielle", "Kacey Musgraves", "Self Esteem"], with: ["Oliver", "Tai", "Mum"] },
  { artist: "Jessie Ware",        venue: "Alexandra Palace",         city: "London", date: "2023-11-17", openers: ["METTE", "Bestley"], with: ["Oliver"] },
  { artist: "Baby Queen",         venue: "O2 Forum Kentish Town",    city: "London", date: "2023-11-15", openers: ["Viji"], with: ["Devangini"] },
  { artist: "Loreen",             venue: "Electric Brixton",         city: "London", date: "2023-11-10", openers: [], with: ["Oliver"] },
  { artist: "Maisie Peters",      venue: "OVO Arena Wembley",        city: "London", date: "2023-11-03", openers: ["Gretta Ray"], guests: ["Ed Sheeran"] },
  { artist: "Charli XCX",         venue: "The O2",                  city: "London", date: "2024-11-28", openers: ["Shygirl"], guests: ["Robyn", "Caroline Polachek", "Yung Lean", "George Daniel"], with: ["Oliver", "George"] },
  { artist: "Rachel Chinouriri",  venue: "O2 Forum Kentish Town",   city: "London", date: "2024-11-16", openers: ["Leonie Biney", "Rockket"], guests: ["Cat Burns"], with: ["Devangini"] },
  { artist: "Aiko",               venue: "O2 Academy Islington",    city: "London", date: "2024-11-14", openers: ["TEYA"], with: ["Oliver"] },
  { artist: "Griff",              venue: "Alexandra Palace",         city: "London", date: "2024-11-13", openers: ["Aziya"], guests: ["Holly Humberstone"], with: ["Devangini"] },
  { artist: "Leigh-Anne",         venue: "KOKO",                    city: "London", date: "2024-10-28", openers: ["MNELIA"], with: ["Devangini"] },
  { artist: "Prateek Kuhad",      venue: "O2 Forum Kentish Town",   city: "London", date: "2024-10-18", openers: [], with: ["Devangini"] },
  { artist: "Marina Satti",       venue: "Electric Ballroom",       city: "London", date: "2024-10-15", openers: ["Theanò"], with: ["Oliver"] },
  { artist: "Chappell Roan",      venue: "O2 Academy Brixton",      city: "London", date: "2024-09-19", openers: [], with: ["Oliver"] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-08-16", openers: ["Paramore", "Holly Humberstone"], with: ["Oliver", "Daniel", "George"] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-06-23", openers: ["Paramore", "Benson Boone"], guests: ["Gracie Abrams"], with: ["Devangini"] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-06-21", openers: ["Paramore", "METTE"], with: ["Oliver", "Avish", "Ben"] },
  { festival: "Eurovision Song Contest (Semi-Final 2)", venue: "Malmö Arena", city: "Malmö", date: "2024-05-09", artists: ["5miinust", "Aiko", "Angelina Mango", "Besa", "Charlotte Perrelli", "Dons", "Eden Golan", "Frans", "Gåte", "Helena Paparizou", "Herreys", "Joost", "Kaleen", "Käärijä", "Ladaniva", "MEGARA", "Marina Satti", "Mustii", "Nebulossa", "Nemo", "Nutsa Buzaladze", "Puuluup", "Saba", "Sarah Bonnici", "Sertab Erener", "Shirley Clamp", "Slimane"], with: ["Oliver"] },
  { festival: "Eurovision Song Contest (Final - Jury Show)", venue: "Malmö Arena", city: "Malmö", date: "2024-05-10", artists: ["Alcazar", "Alyona Alyona", "Angelina Mango", "Baby Lasagna", "Bambie Thug", "Björn Skifs", "Charlotte Perrelli", "Conchita Wurst", "Dons", "Eden Golan", "Gåte", "Iolanda", "Isaak", "Jerry Heil", "Kaleen", "Ladaniva", "Loreen", "Marcus & Martinus", "Marina Satti", "Nebulossa", "Nemo", "Nutsa Buzaladze", "Olly Alexander", "Puuluup", "Raiven", "Shirley Clamp", "Silia Kapsis", "Silvester Belt", "Slimane", "Tali", "Teya Dora", "Windows95man"], with: ["Oliver"] },
  { festival: "Eurovision in Concert", venue: "AFAS Live", city: "Amsterdam", date: "2024-04-13", artists: ["Aiko", "Alexander Rybak", "Alyona Alyona", "Angelina Mango", "Baby Lasagna", "Bambie Thug", "Besa", "Charlotte Perrelli", "Dons", "Gåte", "Hera Björk", "Isaak", "Jerry Heil", "Joost", "Kaleen", "Luna", "Marcus & Martinus", "MEGARA", "Mustii", "Natalia Barbu", "Nebulossa", "Nemo", "Nutsa Buzaladze", "Olly Alexander", "Raiven", "Saba", "Sarah Bonnici", "Silia Kapsis", "Silvester Belt", "Slimane", "Tali", "Teya Dora", "Windows95man"], with: ["Oliver", "Avish", "Tai"] },
  { festival: "London Eurovision Party", venue: "HERE at Outernet", city: "London", date: "2025-04-13", artists: ["ADONXS", "Dolly Style", "Electro Velvet", "EMMY", "Erika Vikman", "Gabry Ponte", "Go-Jo", "JJ", "Jerry Heil", "Justyna Steczkowska", "KAJ", "Kaleen", "Katarsis", "KEiiNO", "Klemen", "Kyle Alessandro", "Laura Thorn", "Maria Sur", "Marko Bošnak", "Melody", "Miriana Conte", "Nina Žižić", "Princ", "Red Sebastian", "Remember Monday", "Shkodra Elektronike", "Sissal", "Tautumeitas", "VASIL", "Væb", "Vladana"], with: ["Devangini"] },
  { artist: "Loreen",          venue: "Eventim Apollo",           city: "London", date: "2025-03-19", openers: ["Luna"], with: ["Felix"] },
  { artist: "Joost",           venue: "Electric Brixton",          city: "London", date: "2025-03-14", openers: [], with: ["Oliver", "Felix"] },
  { artist: "Omar Rudberg",    venue: "O2 Shepherd's Bush Empire", city: "London", date: "2025-02-05", openers: ["Say Now"], with: ["Oliver"] },
  { artist: "RAYE",            venue: "The O2",             city: "London", date: "2026-02-26", openers: ["Absolutely", "Amma"], with: ["Oliver"] },
  { artist: "Magdalena Bay",   venue: "O2 Academy Brixton", city: "London", date: "2026-02-10", openers: ["Allie X"], with: ["Oliver"] },
  { artist: "Allie X",         venue: "KOKO",               city: "London", date: "2024-05-28", openers: ["Tei Shi"], with: ["Oliver", "Devangini"] },
  { festival: "London Eurovision Party", venue: "HERE at Outernet", city: "London", date: "2024-04-07", artists: ["5miinust", "Aiko", "Angelina Mango", "Baby Lasagna", "Bambie Thug", "Conchita Wurst", "Dons", "Gåte", "Gustaph", "Isaak", "Jacqline", "Kaleen", "KEiiNO", "Lucie Jones", "Luna", "Marcus & Martinus", "MEGARA", "Michael Rice", "Mustii", "Natalia Barbu", "Nutsa Buzaladze", "Olly Alexander", "Puuluup", "Raiven", "Rosa Linn", "Saba", "Sarah Bonnici", "Silvester Belt", "Slimane", "STAND UNIQU3", "Windows95man"] },
  { artist: "Rina Sawayama",   venue: "Roundhouse",         city: "London", date: "2021-11-17", openers: ["HANA", "Ama Jones"], with: ["Oliver"] },
  { festival: "Jingle Bell Ball", venue: "The O2",                  city: "London",    date: "2019-12-08", headliners: ["Taylor Swift", "Sam Smith"], support: ["AJ Tracey", "Anne-Marie", "Becky Hill", "Ella Eyre", "Ella Henderson", "Hayley May", "Joel Corry", "Mabel", "Marvin Humes", "RANI", "Sam Feldt", "Sigala", "The Script", "Tom Walker"], with: ["Oliver", "Tai", "Ben"] },
  { artist: "Jess Glynne",      venue: "Wembley Stadium",          city: "London",    date: "2018-10-14", openers: [], note: "NFL London Pre-Game Performance", with: ["Jack", "Tai"] },
  { festival: "Eurovision Song Contest (Final - Family Show)", venue: "Globen", city: "Stockholm", date: "2016-05-14", artists: ["Justin Timberlake", "Amir", "Barei", "Dami Im", "Donny Montell", "Douwe Bob", "Francesca Michielin", "Frans", "Freddie", "Gabriela Guncikova", "Hovi Star", "Ira Losco", "Iveta Mukuchyan", "Jamala", "Jamie-Lee Kriewitz", "Joe & Jake", "Justs", "Laura Tesoro", "Måns Zelmerlöw", "Michał Szpak", "Minus One", "Nina Kraljic", "Petra Mede", "Poli Genova", "Samra", "Sanja Vucic", "Sergey Lazarev", "Young Georgian Lolitaz", "ZOË"], with: ["Mum"] },
];
