const CONCERTS = [
  { artist: "Sigrid",          venue: "Roundhouse",           city: "London", date: "2026-03-13", openers: [] },
  { artist: "Lorde",           venue: "The O2",               city: "London", date: "2025-11-17", openers: ["The Japanese House"] },
  { artist: "Katy Perry",      venue: "The O2",               city: "London", date: "2025-10-14", openers: [] },
  { artist: "Rose Gray",       venue: "Village Underground",  city: "London", date: "2025-10-13", openers: [] },
  { artist: "Erika Vikman",    venue: "The Garage",           city: "London", date: "2025-10-04", openers: [] },
  { artist: "Lady Gaga",       venue: "The O2",               city: "London", date: "2025-10-02", openers: [] },
  { artist: "BLACKPINK",       venue: "Wembley Stadium",      city: "London", date: "2025-08-15", openers: [] },
  { artist: "Camila Cabello",  venue: "Eventim Apollo",       city: "London", date: "2025-07-08", openers: [] },
  { artist: "Dua Lipa",        venue: "Wembley Stadium",          city: "London", date: "2025-06-20", openers: ["Dove Cameron"], guests: ["Jamiroquai"] },
  { artist: "Beyoncé",         venue: "Tottenham Hotspur Stadium", city: "London", date: "2025-06-05", openers: [] },
  { festival: "BST Hyde Park", venue: "Hyde Park",                 city: "London", date: "2025-06-27", headliners: ["Olivia Rodrigo"], support: ["girl in red", "The Last Dinner Party", "Between Friends"], guests: ["Ed Sheeran"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-22", openers: ["Say Now", "DJ Adam Theo"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-19", openers: ["DJ Adam Theo"] },
  { artist: "Nemo",            venue: "O2 Academy Islington", city: "London", date: "2025-11-13", openers: ["Punchbag"] },
  { artist: "Zara Larsson",    venue: "OVO Arena Wembley",    city: "London", date: "2025-11-05", openers: ["Omar Rudberg"] },
  { festival: "BST Hyde Park",         venue: "Hyde Park", city: "London",    date: "2025-07-05", headliners: ["Sabrina Carpenter"], support: ["Clairo", "beabadoobee"] },
  { artist: "Charli XCX",         venue: "HERE at Outernet",        city: "London", date: "2024-06-07", openers: [] },
  { artist: "Olivia Rodrigo",     venue: "The O2",                  city: "London", date: "2024-05-14", openers: ["Remi Wolf"] },
  { artist: "KEiiNO",             venue: "Royal Vauxhall Tavern",   city: "London", date: "2024-04-06", openers: [] },
  { artist: "Griff",              venue: "Roundhouse",               city: "London", date: "2024-04-02", openers: [] },
  { artist: "Allie X",            venue: "Rough Trade East",         city: "London", date: "2024-02-28", openers: [] },
  { artist: "Zara Larsson",       venue: "Roundhouse",               city: "London", date: "2024-02-22", openers: ["Yaeger"] },
  { artist: "Charli XCX",         venue: "The O2",                  city: "London", date: "2024-11-28", openers: ["Shygirl"], guests: ["Robyn", "Caroline Polachek", "Yung Lean", "George Daniel"] },
  { artist: "Rachel Chinouriri",  venue: "O2 Forum Kentish Town",   city: "London", date: "2024-11-16", openers: ["Leonie Biney", "Rockket"], guests: ["Cat Burns"] },
  { artist: "Aiko",               venue: "O2 Academy Islington",    city: "London", date: "2024-11-14", openers: ["Teya"] },
  { artist: "Griff",              venue: "Alexandra Palace",         city: "London", date: "2024-11-13", openers: ["Aziya"], guests: ["Holly Humberstone"] },
  { artist: "Leigh-Anne",         venue: "KOKO",                    city: "London", date: "2024-10-28", openers: ["MNELIA"] },
  { artist: "Prateek Kuhad",      venue: "O2 Forum Kentish Town",   city: "London", date: "2024-10-18", openers: [] },
  { artist: "Marina Satti",       venue: "Electric Ballroom",       city: "London", date: "2024-10-15", openers: ["Theanò"] },
  { artist: "Chappell Roan",      venue: "O2 Academy Brixton",      city: "London", date: "2024-09-19", openers: [] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-08-16", openers: ["Paramore", "Holly Humberstone"] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-06-23", openers: ["Paramore", "Benson Boone"], guests: ["Gracie Abrams"] },
  { artist: "Taylor Swift",       venue: "Wembley Stadium",         city: "London", date: "2024-06-21", openers: ["Paramore", "METTE"] },
  { festival: "Eurovision in Concert", venue: "AFAS Live", city: "Amsterdam", date: "2024-04-13", artists: ["Aiko", "Alexander Rybak", "Alyona Alyona", "Angelina Mango", "Baby Lasagna", "Bambie Thug", "Besa", "Charlotte Perrelli", "Dons", "Gåte", "Hera Björk", "Isaak", "Jerry Heil", "Joost", "Kaleen", "Luna", "Marcus & Martinus", "MEGARA", "Mustii", "Natalia Barbu", "Nebulossa", "Nemo", "Nutsa Buzaladze", "Olly Alexander", "Raiven", "Saba", "Sarah Bonnici", "Silia Kapsis", "Silvester Belt", "Slimane", "Tali", "Teya Dora", "Windows95man"] },
  { artist: "Loreen",          venue: "Eventim Apollo",           city: "London", date: "2025-03-19", openers: ["Luna"] },
  { artist: "Joost",           venue: "Electric Brixton",          city: "London", date: "2025-03-14", openers: [] },
  { artist: "Omar Rudberg",    venue: "O2 Shepherd's Bush Empire", city: "London", date: "2025-02-05", openers: ["Say Now"] },
  { artist: "RAYE",            venue: "The O2",             city: "London", date: "2026-02-26", openers: ["Absolutely", "Amma"] },
  { artist: "Magdalena Bay",   venue: "O2 Academy Brixton", city: "London", date: "2026-02-10", openers: ["Allie X"] },
  { artist: "Allie X",         venue: "KOKO",               city: "London", date: "2024-05-28", openers: ["Tei Shi"] },
  { artist: "Rina Sawayama",   venue: "Roundhouse",         city: "London", date: "2021-11-17", openers: ["HANA", "Ama Jones"] },
];