const CONCERTS = [
  { artist: "Sigrid",          venue: "Roundhouse",           city: "London", date: "2026-03-13", openers: [] },
  { artist: "Lorde",           venue: "The O2",               city: "London", date: "2025-11-17", openers: ["The Japanese House"] },
  { artist: "Katy Perry",      venue: "The O2",               city: "London", date: "2025-10-14", openers: [] },
  { artist: "Rose Gray",       venue: "Village Underground",  city: "London", date: "2025-10-13", openers: [] },
  { artist: "Erika Vikman",    venue: "The Garage",           city: "London", date: "2025-10-04", openers: [] },
  { artist: "Lady Gaga",       venue: "The O2",               city: "London", date: "2025-10-02", openers: [] },
  { artist: "BLACKPINK",       venue: "Wembley Stadium",      city: "London", date: "2025-08-15", openers: [] },
  { artist: "Camila Cabello",  venue: "Eventim Apollo",       city: "London", date: "2025-07-08", openers: [] },
  { festival: "BST Hyde Park", venue: "Hyde Park",            city: "London", date: "2025-06-27", headliners: ["Olivia Rodrigo"], support: ["Girl in Red", "The Last Dinner Party", "Between Friends"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-22", openers: ["Say Now", "DJ Adam Theo"] },
  { artist: "Jade",            venue: "Roundhouse",           city: "London", date: "2025-10-19", openers: ["DJ Adam Theo"] },
  { artist: "Nemo",            venue: "O2 Academy Islington", city: "London", date: "2025-11-13", openers: ["Punchbag"] },
  { artist: "Zara Larsson",    venue: "OVO Arena Wembley",    city: "London", date: "2025-11-05", openers: ["Omar Rudberg"] },
  { festival: "BST Hyde Park",         venue: "Hyde Park", city: "London",    date: "2025-07-05", headliners: ["Sabrina Carpenter"], support: ["Clairo", "beabadoobee"] },
  { festival: "Eurovision in Concert", venue: "AFAS Live", city: "Amsterdam", date: "2024-04-13", artists: ["Joost", "Besa", "Raiven", "Aiko", "Alexander Rybak", "Slimane", "Natalia Barbu", "Luna", "Saba", "Silvester Belt", "Jerry Heil", "Baby Lasagna", "Isaak", "Nemo", "Olly Alexander", "Windows95man", "Teya Dora", "Mustii", "Hera Björk", "Charlotte Perrelli", "Tali", "Gåte", "Nebulossa", "Alyona Alyona", "Dons", "Bambie Thug", "MEGARA", "Nutsa Buzaladze", "Sarah Bonnici", "Angelina Mango", "Kaleen", "Silia Kapsis", "Marcus & Martinus"] },
  { artist: "RAYE",            venue: "The O2",             city: "London", date: "2026-02-26", openers: ["Absolutely", "Amma"] },
  { artist: "Magdalena Bay",   venue: "O2 Academy Brixton", city: "London", date: "2026-02-10", openers: ["Allie X"] },
  { artist: "Allie X",         venue: "KOKO",               city: "London", date: "2024-05-28", openers: ["Tei Shi"] },
  { artist: "Rina Sawayama",   venue: "Roundhouse",         city: "London", date: "2021-11-17", openers: ["HANA", "Ama Jones"] },
];
