const PLAYER_PICKS = [
  {
    seasonId: 1,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 2,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 3,
    star:      "Brandon Quinton",
    secondary: "Lex van den Berghe",
    preMerge:  "Linda Spencer",
    wantBack:  "Brandon Quinton",
  },
  {
    seasonId: 4,
    star:      "Kathy Vavrick O'Brien",
    secondary: "Rob Mariano",
    preMerge:  "Gina Crews",
    wantBack:  "Sean Rector",
  },
  {
    seasonId: 5,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 6,
    star:      "Rob Cesternino",
    secondary: "Deena Bennett",
    preMerge:  "JoAnna Ward",
    wantBack:  "Deena Bennett",
  },
  {
    seasonId: 7,
    star:      "Sandra Diaz-Twine",
    secondary: "Jon Dalton",
    preMerge:  "Ryan Shoulders",
    wantBack:  "Burton Roberts",
  },
  {
    seasonId: 47,
    star:      "Genevieve Mushaluk",
    secondary: "Andy Rueda",
    preMerge:  "Anika Dhar",
    wantBack:  "Sam Phalen",
  },
];
