const PLAYER_PICKS = [
  {
    seasonId: 1,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 2,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 3,
    star:      "Brandon Quinton",
    secondary: "Lex van den Berghe",
    preMerge:  "Linda Spencer",
    wantBack:  "Brandon Quinton",
  },
  {
    seasonId: 4,
    star:      "Kathy Vavrick O'Brien",
    secondary: "Rob Mariano",
    preMerge:  "Gina Crews",
    wantBack:  "Sean Rector",
  },
  {
    seasonId: 5,
    star:      "",
    secondary: "",
    preMerge:  "",
    wantBack:  "",
  },
  {
    seasonId: 6,
    star:      "Rob Cesternino",
    secondary: "Deena Bennett",
    preMerge:  "JoAnna Ward",
    wantBack:  "Deena Bennett",
  },
  {
    seasonId: 7,
    star:      "Sandra Diaz-Twine",
    secondary: "Jon Dalton",
    preMerge:  "Ryan Shoulders",
    wantBack:  "Burton Roberts",
  },
  {
    seasonId: 39,
    star:      "Kellee Kim",
    secondary: "Noura Salman",
    preMerge:  "Vince Moua",
    wantBack:  "Kellee Kim",
  },
  {
    seasonId: 40,
    star:      "Tony Vlachos",
    secondary: "Michele Fitzgerald",
    preMerge:  "Parvati Shallow",
    wantBack:  "Sophie Clarke",
  },
  {
    seasonId: 41,
    star:      "Shan Smith",
    secondary: "Ricard Foyé",
    preMerge:  "JD Robinson",
    wantBack:  "Shan Smith",
  },
  {
    seasonId: 42,
    star:      "Maryanne Oketch",
    secondary: "Omar Zaheer",
    preMerge:  "Zach Wurtenberger",
    wantBack:  "Omar Zaheer",
  },
  {
    seasonId: 44,
    star:      "Carolyn Wiger",
    secondary: "Yam Yam Arocho",
    preMerge:  "Matthew Grinstead-Mayle",
    wantBack:  "Carolyn Wiger",
  },
  {
    seasonId: 47,
    star:      "Genevieve Mushaluk",
    secondary: "Andy Rueda",
    preMerge:  "Anika Dhar",
    wantBack:  "Sam Phalen",
  },
  {
    seasonId: 48,
    star:      "Kamilla Karthigesu",
    secondary: "Kyle Fraser",
    preMerge:  "Thomas Krottinger",
    wantBack:  "Saiounia Hughley",
  },
];
