const CALBUMDAR = {
  2025: [
    { rank: 1,  artist: "Lady Gaga",     album: "MAYHEM",                         songs: ["Disease", "Abracadabra", "Vanish Into You"],                    spotify: "https://open.spotify.com/album/2MHUaRi9OCyTN02SoyRRBJ" },
    { rank: 2,  artist: "JADE",          album: "THAT'S SHOWBIZ BABY!",           songs: ["Angel Of My Dreams", "FUFN (Fuck You For Now)", "Plastic Box"], spotify: "https://open.spotify.com/album/4MR10rSYnclQoPXq6O9sw0" },
    { rank: 3,  artist: "Demi Lovato",   album: "It's Not That Deep",             songs: ["Fast", "Here All Night", "Kiss"],                               spotify: "https://open.spotify.com/album/0bzP9iV2QbM6174JLfGxcc" },
    { rank: 4,  artist: "Rose Gray",     album: "Louder, Please",                 songs: ["Damn", "Wet & Wild", "Angel Of Satisfaction"],                  spotify: "https://open.spotify.com/album/79SqMfih2FN1NaLtZUcccG" },
    { rank: 5,  artist: "Lorde",         album: "Virgin",                         songs: ["Hammer", "What Was That", "Shapeshifter"],                      spotify: "https://open.spotify.com/album/28bHj2enHkHVFLwuWmkwlQ" },
    { rank: 6,  artist: "Zara Larsson",  album: "Midnight Sun",                   songs: ["Midnight Sun", "Girl's Girl", "Hot & Sexy"],                    spotify: "https://open.spotify.com/album/0nte5x6fXd37Nt7jALSmx0" },
    { rank: 7,  artist: "Addison Rae",   album: "Addison",                        songs: ["Diet Pepsi", "Fame is a Gun", "Headphones On"],                 spotify: "https://open.spotify.com/album/2ffVa2UhHUDwMHnr685zJ4" },
    { rank: 8,  artist: "Abor & Tynna", album: "Bittersüß",                      songs: ["Seifenblasen", "Winnetou", "Baller"],                           spotify: "https://open.spotify.com/album/0PrVmVD88Xk509v7BOT6a2" },
    { rank: 9,  artist: "Rebecca Black", album: "SALVATION",                      songs: ["Salvation", "TRUST!", "Sugar Water Cyanide"],                   spotify: "https://open.spotify.com/album/7KeBfU7MZe7LFqgse8blI7" },
    { rank: 10, artist: "ADÉLA",         album: "The Provocateur",                songs: ["Superscar", "SexOnTheBeat", "DeathByDevotion"],                 spotify: "https://open.spotify.com/album/7LWxUjVO8rhvEUQu2cyVgd" },
    { rank: 11, artist: "Reneé Rapp",    album: "BITE ME",                        songs: ["Mad", "Kiss It Kiss It", "Shy"],                                spotify: "https://open.spotify.com/album/6ULnaZahd0zTGVUBVQO6mN" },
    { rank: 12, artist: "Allie X",       album: "Happiness is Going to Get You",  songs: ["Is Anybody Out There?", "7th Floor", "Stay Green"],             spotify: "https://open.spotify.com/album/2MhRCfdhN8os29CovIIsqV" },
    { rank: 13, artist: "Tate McRae",    album: "So Close To What",               songs: ["TIT FOR TAT", "Revolving door", "2 hands"],                     spotify: "https://open.spotify.com/album/4AIX5TN8oT656mgxRwDevJ" },
    { rank: 14, artist: "PinkPantheress", album: "Fancy That",                    songs: ["Illegal", "Tonight", "Stateside"],                              spotify: "https://open.spotify.com/album/3o81FH5FTYVtoBQOZr3T7y" },
    { rank: 15, artist: "Cat Burns",     album: "How To Be Human",                songs: ["Sad Forever", "GIRLS!", "There's Just Something About Her"],    spotify: "https://open.spotify.com/album/5l7VNmhvyYndw2XNxH9GFe" },
    { rank: 16, artist: "Miley Cyrus",   album: "Something Beautiful",            songs: ["Something Beautiful", "End of the World", "Easy Lover"],        spotify: "https://open.spotify.com/album/7h7smPzBYx8LOLI3ncM3vQ" },
    { rank: 17, artist: "Annalisa",      album: "MA IO SONO FUOCO",               songs: ["Dipende", "Delusa", "Maschio"],                                  spotify: "https://open.spotify.com/album/5whsiw7yvWXul5t8sWYYLQ" },
    { rank: 18, artist: "Eli",           album: "Stage Girl",                     songs: ["Stars (Lullabye)", "Girl of Your Dreams", "Somebody I'm Not"],  spotify: "https://open.spotify.com/album/6WOa0ML0MubR3Vz2QwTI6R" },
    { rank: 19, artist: "Nemo",          album: "Arthouse",                       songs: ["God's A Raver", "Hocus Pocus", "The Code"],                     spotify: "https://open.spotify.com/album/7II243HQI2I0gvCSOLsWN2" },
    { rank: 20, artist: "Audrey Hobert", album: "Who's the Clown?",               songs: ["Sue me", "Thirst Trap", "Shooting star"],                       spotify: "https://open.spotify.com/album/6unMpOoIJqsLxuoTEFqdfP" },
    { rank: 21, artist: "Marina",        album: "PRINCESS OF POWER",              songs: ["PRINCESS OF POWER", "CUNTISSIMO", "CUPID'S GIRL"],              spotify: "https://open.spotify.com/album/2rjfRdmVDBMFT5mamSsVeU" },
    { rank: 22, artist: "Blusher",       album: "RACER",                          songs: ["RACER", "DON'T LOOK AT ME LIKE THAT", "WHATEVERWHATEVER"],      spotify: "https://open.spotify.com/album/6vay9YuOMKK5Pij8urGx8x" },
    { rank: 23, artist: "KATSEYE",       album: "BEAUTIFUL CHAOS",                songs: ["Gnarly", "Gabriela", "M.I.A"],                                  spotify: "https://open.spotify.com/album/4llrXTk6u4QYI1j7KHIsCx" },
    { rank: 24, artist: "Perrie",        album: "Perrie",                         songs: ["If He Wanted To He Would", "Rocket Scientist", "Absofuckinglutely"], spotify: "https://open.spotify.com/album/40D8mOfQknlA99Q7QpLJEC" },
  ],
  2024: [
    { rank: 1,  artist: "Griff", album: "Vertigo", songs: ["Miss Me Too", "Anything", "Cycles"], spotify: "https://open.spotify.com/album/3VA9PnquCzG4E2GHgBzFQE" },
    { rank: 2,  artist: "Rachel Chinouriri", album: "What A Devastating Turn of Events", songs: ["Garden of Eden", "The Hills", "Never Need Me"], spotify: "https://open.spotify.com/album/1Td1oiZTQFYR7N1QX00uhr" },
    { rank: 3,  artist: "Charli xcx", album: "BRAT", songs: ["Talk talk", "Girl so confusing featuring lorde", "365"], spotify: "https://open.spotify.com/album/2lIZef4lzdvZkiiCzvPKj7" },
    { rank: 4,  artist: "Allie X", album: "Girl With No Face", songs: ["Weird World", "Off With Her Tits", "Black Eye"], spotify: "https://open.spotify.com/album/10o3OFqQt0gqemtIcCh72x" },
    { rank: 5,  artist: "Dua Lipa", album: "Radical Optimism", songs: ["Houdini", "Training Season", "Illusion"], spotify: "https://open.spotify.com/album/1Mo92916G2mmG7ajpmSVrc" },
    { rank: 6,  artist: "Remi Wolf", album: "Big Ideas", songs: ["Cinderella", "Soup", "Toro"], spotify: "https://open.spotify.com/album/7HQOEMCDGKY8eJyQPdsnYH" },
    { rank: 7,  artist: "Sabrina Carpenter", album: "Short n' Sweet", songs: ["Taste", "Bed Chem", "Espresso"], spotify: "https://open.spotify.com/album/3iPSVi54hsacKKl1xIR2eH" },
    { rank: 8,  artist: "FLETCHER", album: "In Search Of The Antidote", songs: ["Two Things Can Be True", "Eras Of Us", "Attached To You"], spotify: "https://open.spotify.com/album/1ZXvAPiGoqDXWsLHd3oZ8Q" },
    { rank: 9,  artist: "Olivia Rodrigo", album: "GUTS (spilled)", songs: ["obsessed", "girl i've always been", "so american"], spotify: "https://open.spotify.com/album/1D06fz3cuob62ysTS8k6gu" },
    { rank: 10, artist: "Ariana Grande", album: "eternal sunshine", songs: ["bye", "yes and?", "we can't be friends (wait for your love)"], spotify: "https://open.spotify.com/album/5EYKrEDnKhhcNxGedaRQeK" },
    { rank: 11, artist: "Zara Larsson", album: "VENUS", songs: ["Can't Tame Her", "You Love Who You Love", "End Of Time"], spotify: "https://open.spotify.com/album/0qqZ6HD72So93exL9rH7zi" },
    { rank: 12, artist: "Leigh-Anne", album: "No Hard Feelings", songs: ["Stealin' Love", "OMG", "Anticipate"], spotify: "https://open.spotify.com/album/5FLuHwbit7X3hXqXB1j6Mb" },
    { rank: 13, artist: "girl in red", album: "I'M DOING IT AGAIN BABY!", songs: ["DOING IT AGAIN BABY", "Too Much", "You Need Me Now?"], spotify: "https://open.spotify.com/album/5QaKu3YoUJNglyaKixaegf" },
    { rank: 14, artist: "ROSÉ", album: "rosie", songs: ["toxic till the end", "drinks or coffee", "APT."], spotify: "https://open.spotify.com/album/7kFyd5oyJdVX2pIi6P4iHE" },
    { rank: 15, artist: "Lena", album: "Loyal to myself", songs: ["Loyal to myself", "I miss u", "Drug worth doing"], spotify: "https://open.spotify.com/album/3rH9pkjNKjQvW72bo4xWUm" },
    { rank: 16, artist: "Billie Eilish", album: "HIT ME HARD AND SOFT", songs: ["LUNCH", "BIRDS OF A FEATHER", "THE DINER"], spotify: "https://open.spotify.com/album/7aJuG4TFXa2hmE4z1yxc3n" },
    { rank: 17, artist: "Aiko", album: "AIKONIC", songs: ["Hunger", "White Flag", "Pedestal"], spotify: "https://open.spotify.com/album/3D3e4B1bGx5FWmCCWbHAYv" },
    { rank: 18, artist: "Taylor Swift", album: "THE TORTURED POETS DEPARTMENT", songs: ["Fortnight", "Florida!!!", "The Alchemy"], spotify: "https://open.spotify.com/album/5H7ixXZfsNMGbIE5OBSpcb" },
    { rank: 19, artist: "FLO", album: "Access All Areas", songs: ["In My Bag", "Walk Like This", "Check"], spotify: "https://open.spotify.com/album/3wSWMuHQOJ2gU22t5sCouR" },
    { rank: 20, artist: "Tyla", album: "TYLA", songs: ["Safer", "Water", "ART"], spotify: "https://open.spotify.com/album/3KGVOGmIbinlrR97aFufGE" },
    { rank: 21, artist: "TEYA", album: "Grandma On The Dancefloor", songs: ["Behind The Scenes", "To-Do List", "Immigrant Child"], spotify: "https://open.spotify.com/album/6KWFefpEa1TShCfDMU2ETn" },
    { rank: 22, artist: "Beyoncé", album: "COWBOY CARTER", songs: ["TEXAS HOLD 'EM", "II MOST WANTED", "YA YA"], spotify: "https://open.spotify.com/album/6BzxX6zkDsYKFJ04ziU5xQ" },
    { rank: 23, artist: "AURORA", album: "What Happened To The Heart?", songs: ["Your Blood", "Some Type Of Skin", "When The Dark Dresses Lightly"], spotify: "https://open.spotify.com/album/0bI3iaA6A68DTRcUoOyQx5" },
    { rank: 24, artist: "Alessandra", album: "Best Year Of My Life", songs: ["Pretty Devil", "Bad Bitch", "Queen Of Kings"], spotify: "https://open.spotify.com/album/5FhhSgLoO7YC6nYZtsZ1bc" },
  ],
};
