const CALBUMDAR = {
  2024: [
    { rank: 1,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 2,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 3,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 4,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 5,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 6,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 7,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 8,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 9,  artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 10, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 11, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 12, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 13, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 14, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 15, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 16, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 17, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 18, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 19, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 20, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 21, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 22, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 23, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
    { rank: 24, artist: "Artist",  album: "Album Title", cover: "", songs: ["Song 1", "Song 2", "Song 3"], note: "" },
  ],
};
