const CALBUMDAR = {
  2025: [
    { rank: 1,  artist: "Lady Gaga",   album: "MAYHEM",               cover: "../images/advent-calbumdar/mayhem.jpg",           songs: ["Disease", "Abracadabra", "Vanish Into You"],              spotify: "https://open.spotify.com/album/2MHUaRi9OCyTN02SoyRRBJ", note: "" },
    { rank: 2,  artist: "JADE",        album: "THAT'S SHOWBIZ BABY!", cover: "../images/advent-calbumdar/thats-showbiz-baby.jpg", songs: ["Angel Of My Dreams", "FUFN (Fuck You For Now)", "Plastic Box"], spotify: "https://open.spotify.com/album/4MR10rSYnclQoPXq6O9sw0", note: "" },
    { rank: 3,  artist: "Demi Lovato", album: "It's Not That Deep",   cover: "../images/advent-calbumdar/its-not-that-deep.jpg", songs: ["Fast", "Here All Night", "Kiss"],                        spotify: "https://open.spotify.com/album/0bzP9iV2QbM6174JLfGxcc", note: "" },
    { rank: 4,  artist: "Rose Gray",   album: "Louder, Please",       cover: "../images/advent-calbumdar/louder-please.jpg",      songs: ["Damn", "Wet & Wild", "Angel Of Satisfaction"],           spotify: "https://open.spotify.com/album/79SqMfih2FN1NaLtZUcccG", note: "" },
    { rank: 5,  artist: "Lorde",      album: "Virgin",               cover: "../images/advent-calbumdar/virgin.jpg",             songs: ["Hammer", "What Was That", "Shapeshifter"],               spotify: "https://open.spotify.com/album/28bHj2enHkHVFLwuWmkwlQ", note: "" },
    { rank: 6,  artist: "Zara Larsson", album: "Midnight Sun",       cover: "../images/advent-calbumdar/midnight-sun.jpg",       songs: ["Midnight Sun", "Girl's Girl", "Hot & Sexy"],             spotify: "https://open.spotify.com/album/0nte5x6fXd37Nt7jALSmx0", note: "" },
    { rank: 7,  artist: "Addison Rae",  album: "Addison",            cover: "../images/advent-calbumdar/addison.jpg",            songs: ["Diet Pepsi", "Fame is a Gun", "Headphones On"],          spotify: "https://open.spotify.com/album/2ffVa2UhHUDwMHnr685zJ4", note: "" },
    { rank: 8,  artist: "Abor & Tynna", album: "Bittersüß",         cover: "../images/advent-calbumdar/bittersuss.jpg",         songs: ["Seifenblasen", "Winnetou", "Baller"],                    spotify: "https://open.spotify.com/album/0PrVmVD88Xk509v7BOT6a2", note: "" },
    { rank: 9,  artist: "Rebecca Black", album: "SALVATION",        cover: "../images/advent-calbumdar/salvation.jpg",          songs: ["Salvation", "TRUST!", "Sugar Water Cyanide"],            spotify: "https://open.spotify.com/album/7KeBfU7MZe7LFqgse8blI7", note: "" },
    { rank: 10, artist: "ADÉLA",        album: "The Provocateur",   cover: "../images/advent-calbumdar/the-provocateur.jpg",    songs: ["Superscar", "SexOnTheBeat", "DeathByDevotion"],          spotify: "https://open.spotify.com/album/7LWxUjVO8rhvEUQu2cyVgd", note: "" },
    { rank: 11, artist: "Reneé Rapp",   album: "BITE ME",           cover: "../images/advent-calbumdar/bite-me.jpg",            songs: ["Mad", "Kiss It Kiss It", "Shy"],                         spotify: "https://open.spotify.com/album/6ULnaZahd0zTGVUBVQO6mN", note: "" },
    { rank: 12, artist: "Allie X",        album: "Happiness is Going to Get You", cover: "../images/advent-calbumdar/happiness-is-going-to-get-you.jpg", songs: ["Is Anybody Out There?", "7th Floor", "Stay Green"], spotify: "https://open.spotify.com/album/2MhRCfdhN8os29CovIIsqV", note: "" },
    { rank: 13, artist: "Tate McRae",    album: "So Close To What",    cover: "../images/advent-calbumdar/so-close-to-what.jpg",    songs: ["TIT FOR TAT", "Revolving door", "2 hands"],             spotify: "https://open.spotify.com/album/4AIX5TN8oT656mgxRwDevJ", note: "" },
    { rank: 14, artist: "PinkPantheress", album: "Fancy That",         cover: "../images/advent-calbumdar/fancy-that.jpg",          songs: ["Illegal", "Tonight", "Stateside"],                      spotify: "https://open.spotify.com/album/3o81FH5FTYVtoBQOZr3T7y", note: "" },
    { rank: 15, artist: "Cat Burns",    album: "How To Be Human",     cover: "../images/advent-calbumdar/how-to-be-human.jpg",     songs: ["Sad Forever", "GIRLS!", "There's Just Something About Her"], spotify: "https://open.spotify.com/album/5l7VNmhvyYndw2XNxH9GFe", note: "" },
    { rank: 16, artist: "Miley Cyrus", album: "Something Beautiful",  cover: "../images/advent-calbumdar/something-beautiful.jpg", songs: ["Something Beautiful", "End of the World", "Easy Lover"], spotify: "https://open.spotify.com/album/7h7smPzBYx8LOLI3ncM3vQ", note: "" },
    { rank: 17, artist: "Annalisa",   album: "MA IO SONO FUOCO",     cover: "../images/advent-calbumdar/ma-io-sono-fuoco.jpg",    songs: ["Dipende", "Delusa", "Maschio"],                          spotify: "https://open.spotify.com/album/5whsiw7yvWXul5t8sWYYLQ", note: "" },
    { rank: 18, artist: "Eli",       album: "Stage Girl",           cover: "../images/advent-calbumdar/stage-girl.jpg",          songs: ["Stars (Lullabye)", "Girl of Your Dreams", "Somebody I'm Not"], spotify: "https://open.spotify.com/album/6WOa0ML0MubR3Vz2QwTI6R", note: "" },
    { rank: 19, artist: "Nemo",          album: "Arthouse",           cover: "../images/advent-calbumdar/arthouse.jpg",              songs: ["God's A Raver", "Hocus Pocus", "The Code"],            spotify: "https://open.spotify.com/album/7II243HQI2I0gvCSOLsWN2", note: "" },
    { rank: 20, artist: "Audrey Hobert", album: "Who's the Clown?",  cover: "../images/advent-calbumdar/whos-the-clown.jpg",        songs: ["Sue me", "Thirst Trap", "Shooting star"],               spotify: "https://open.spotify.com/album/6unMpOoIJqsLxuoTEFqdfP", note: "" },
    { rank: 21, artist: "Marina",        album: "PRINCESS OF POWER", cover: "../images/advent-calbumdar/princess-of-power.jpg",     songs: ["PRINCESS OF POWER", "CUNTISSIMO", "CUPID'S GIRL"],      spotify: "https://open.spotify.com/album/2rjfRdmVDBMFT5mamSsVeU", note: "" },
    { rank: 22, artist: "Blusher",      album: "RACER",             cover: "../images/advent-calbumdar/racer.jpg",                 songs: ["RACER", "DON'T LOOK AT ME LIKE THAT", "WHATEVERWHATEVER"], spotify: "https://open.spotify.com/album/6vay9YuOMKK5Pij8urGx8x", note: "" },
    { rank: 23, artist: "KATSEYE",     album: "BEAUTIFUL CHAOS",   cover: "../images/advent-calbumdar/beautiful-chaos.jpg",       songs: ["Gnarly", "Gabriela", "M.I.A"],                           spotify: "https://open.spotify.com/album/4llrXTk6u4QYI1j7KHIsCx", note: "" },
    { rank: 24, artist: "Perrie",     album: "Perrie",            cover: "../images/advent-calbumdar/perrie.jpg",                songs: ["If He Wanted To He Would", "Rocket Scientist", "Absofuckinglutely"], spotify: "https://open.spotify.com/album/40D8mOfQknlA99Q7QpLJEC", note: "" },
  ],
  2024: [
    { rank: 1,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 2,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 3,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 4,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 5,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 6,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 7,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 8,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 9,  artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 10, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 11, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 12, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 13, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 14, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 15, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 16, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 17, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 18, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 19, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 20, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 21, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 22, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 23, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
    { rank: 24, artist: "Artist",  album: "Album Title", cover: "", songs: [], spotify: "", note: "" },
  ],
};
