const DRAG_SHOWS = [
  {
    date: "2021-09-22",
    venue: "Clapham Grand",
    city: "London",
    event: "Utica & Denali Tour",
    headliners: ["Utica", "Denali"],
    support: ["Sminty Drop", "Ellie Diamond", "Gothy Kendoll", "Krystal Versace", "Scarlett Harlett", "Miss Leigh Ding", "Bay Ken", "Rehab Kendoll"],
    with: ["Oliver"],
  },
  {
    date: "2023-04-09",
    venue: "Heaven",
    city: "London",
    performers: ["Loosey LaDuca"],
    with: ["Oliver"],
  },
  {
    date: "2023-11-13",
    venue: "London Palladium",
    city: "London",
    event: "The Jinkx and Dela Holiday Special",
    headliners: ["Jinkx Monsoon", "BenDeLaCreme"],
    with: ["Devangini"],
  },
  {
    date: "2024-03-08",
    venue: "London Palladium",
    city: "London",
    event: "The Big Reveal",
    headliners: ["Sasha Velour"],
    support: ["Chiyo"],
    with: ["Devangini"],
  },
  {
    date: "2024-04-07",
    venue: "HERE at Outernet",
    city: "London",
    event: "London Eurovision Party",
    performers: ["Conchita Wurst"],
  },
  {
    date: "2024-05-02",
    venue: "O2 Forum Kentish Town",
    city: "London",
    event: "UK vs the World Season 2 Tour",
    performers: ["Marina Summers", "Tia Kofi", "Hannah Conda", "La Grande Dame", "Arantxa Castilla-La Mancha", "Choriza May", "Scarlet Envy", "Gothy Kendoll", "Keta Minaj"],
    outOfDrag: ["Vanity Milan", "Elektra Fence", "Cheryl", "Etcetera Etcetera", "Le Fil", "Just May", "Kitty Scott-Claus", "Ella Vaday"],
    with: ["Devangini"],
  },
  {
    date: "2024-05-30",
    venue: "Clapham Grand",
    city: "London",
    headliners: ["Marina Summers"],
    support: ["La Belle", "Tailor Maid", "Flesh"],
    outOfDrag: ["Hannah Conda"],
    with: ["Devangini"],
  },
  {
    date: "2024-09-19",
    venue: "O2 Academy Brixton",
    city: "London",
    event: "Chappell Roan Concert",
    performers: ["Crayola", "Glew", "Toxiic"],
    with: ["Oliver"],
  },
  {
    date: "2024-09-24",
    venue: "Eventim Apollo",
    city: "London",
    event: "Dead Inside",
    headliners: ["Bianca Del Rio"],
    support: ["Mary Mac"],
    with: ["Devangini"],
  },
  {
    date: "2024-10-19",
    venue: "Clapham Grand",
    city: "London",
    headliners: ["Sapphira Cristál", "Plane Jane", "Morphine Love Dion"],
    outOfDrag: ["Tayce"],
    with: ["Devangini"],
  },
  {
    date: "2024-11-23",
    venue: "Clapham Grand",
    city: "London",
    event: "Nymphia Wind's Banana Ball",
    headliners: ["Nymphia Wind"],
    support: ["A'Whora", "Dosa Cat", "Flesh","Sohpia Stardust", "Juno Birch"],
    with: ["Devangini"],
  },
  {
    date: "2025-04-14",
    venue: "London Palladium",
    city: "London",
    event: "Werq The World",
    headliners: ["Roxxxy Matthews", "Jaida Essence Hall", "Vanessa \"Vanjie\" Mateo", "Marina Summers", "Derrick Barry", "Sasha Velour", "Lawrence Chaney", "Bimini Bon Boulash", "Tayce"],
    support: ["Actavia", "Charra Tea", "Zahira Zapanta", "Kiki Snatch", "Miss Naomi Carter"],
    with: ["Devangini"],
  },
  {
    date: "2025-10-02",
    venue: "Heaven",
    city: "London",
    performers: ["Pasty Kween"],
    with: ["Devangini", "Oliver"],
  },
  {
    date: "2026-03-13",
    venue: "Admiral Duncan",
    city: "London",
    performers: ["Amaya Napa"],
    with: ["Devangini", "Oliver"],
  },
];
