import json
import os
import re

SCRIPT_DIR     = os.path.dirname(os.path.abspath(__file__))
SCROBBLES_FILE = os.path.join(SCRIPT_DIR, "scrobbles.json")
ALBUMS_FILE    = os.path.join(SCRIPT_DIR, "albums.js")
ALIASES_FILE   = os.path.join(SCRIPT_DIR, "album-aliases.json")
CACHE_FILE     = os.path.join(SCRIPT_DIR, "lastfm-cache.js")


def normalize(s):
    return s.lower().replace('\u2018', "'").replace('\u2019', "'")


def va_album_names():
    """Return normalized album names where artist is 'Various Artists'."""
    with open(ALBUMS_FILE) as f:
        src = f.read()
    names = set()
    for obj in re.finditer(r'\{[^}]+\}', src, re.DOTALL):
        text = obj.group()
        if not re.search(r'artist:\s*"Various Artists"', text):
            continue
        m = re.search(r'album:\s*"([^"]+)"', text)
        if m:
            names.add(normalize(m.group(1)))
    return names


def build():
    if not os.path.exists(SCROBBLES_FILE):
        print("scrobbles.json not found — run fetch_scrobbles.py --full first.")
        return

    with open(SCROBBLES_FILE) as f:
        data = json.load(f)

    scrobbles = data.get("scrobbles", [])
    last_fetched = data.get("lastFetched", "")
    va_albums = va_album_names()

    # Build cache: most recent run of 5+ consecutive scrobbles per artist|||album.
    # Various Artists albums key on |||album only (artist varies per track).
    # Process ascending (oldest first) so later runs overwrite earlier ones.
    last_played = {}
    current_key = None
    run_count = 0
    for s in reversed(scrobbles):
        artist = s.get("artist", "").strip()
        album  = s.get("album",  "").strip()
        ts     = s.get("ts", 0)
        if not artist or not album:
            current_key = None
            run_count = 0
            continue
        norm_album = normalize(album)
        if norm_album in va_albums:
            key = "|||" + norm_album
        else:
            key = normalize(artist) + "|||" + norm_album
        if key == current_key:
            run_count += 1
        else:
            current_key = key
            run_count = 1
        if run_count == 5:
            last_played[key] = ts

    # Merge aliases: fold variant keys into canonical, keeping most recent timestamp
    if os.path.exists(ALIASES_FILE):
        with open(ALIASES_FILE) as f:
            aliases = json.load(f)
        for entry in aliases:
            artist       = normalize(entry["artist"])
            canonical_key = artist + "|||" + normalize(entry["canonical"])
            timestamps   = []
            if canonical_key in last_played:
                timestamps.append(last_played[canonical_key])
            for alias in entry["aliases"]:
                alias_key = artist + "|||" + normalize(alias)
                if alias_key in last_played:
                    timestamps.append(last_played.pop(alias_key))
            if timestamps:
                last_played[canonical_key] = max(timestamps)

    # Write JS file
    entries = ",\n  ".join(
        f'"{k.replace(chr(34), chr(92)+chr(34))}": {v}'
        for k, v in sorted(last_played.items())
    )

    js = (
        f"// lastfm-cache.js — generated by build_cache.py\n"
        f"// Last fetched: {last_fetched}\n"
        f"// {len(last_played)} entries (5+ consecutive scrobbles) from {len(scrobbles)} scrobbles\n"
        f"var LASTFM_CACHE = {{\n"
        f"  {entries}\n"
        f"}};\n"
    )

    with open(CACHE_FILE, "w") as f:
        f.write(js)

    print(f"Written {len(last_played)} entries to lastfm-cache.js")


if __name__ == "__main__":
    build()
