#!/usr/bin/env python3
# build_cache.py
# Reads scrobbles.json and writes lastfm-cache.js
#
# Run directly:  python3 build_cache.py
# Or called automatically by fetch_scrobbles.py after a refresh.

import json
import os

SCRIPT_DIR     = os.path.dirname(os.path.abspath(__file__))
SCROBBLES_FILE = os.path.join(SCRIPT_DIR, "scrobbles.json")
CACHE_FILE     = os.path.join(SCRIPT_DIR, "lastfm-cache.js")


def build():
    if not os.path.exists(SCROBBLES_FILE):
        print("scrobbles.json not found — run fetch_scrobbles.py --full first.")
        return

    with open(SCROBBLES_FILE) as f:
        data = json.load(f)

    scrobbles = data.get("scrobbles", [])
    last_fetched = data.get("lastFetched", "")

    # Build artist|||album → most recent timestamp
    # Scrobbles are sorted descending, so the first occurrence of each key is the latest.
    last_played = {}
    for s in scrobbles:
        artist = s.get("artist", "").strip()
        album  = s.get("album",  "").strip()
        ts     = s.get("ts", 0)
        if not artist or not album:
            continue
        key = artist + "|||" + album
        if key not in last_played:
            last_played[key] = ts

    # Write JS file
    entries = ",\n  ".join(
        f'"{k.replace(chr(34), chr(92)+chr(34))}": {v}'
        for k, v in sorted(last_played.items())
    )

    js = (
        f"// lastfm-cache.js — generated by build_cache.py\n"
        f"// Last fetched: {last_fetched}\n"
        f"// {len(last_played)} unique artist/album combinations from {len(scrobbles)} scrobbles\n"
        f"var LASTFM_CACHE = {{\n"
        f"  {entries}\n"
        f"}};\n"
    )

    with open(CACHE_FILE, "w") as f:
        f.write(js)

    print(f"Written {len(last_played)} entries to lastfm-cache.js")


if __name__ == "__main__":
    build()
